version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /DB:/docker-entrypoint-initdb.d/data.sql
    networks:
      - internalnet

  spring:
    image: monaemhamila/devopsbackend
    container_name: test_backend
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - internalnet
    volumes: 
      - /DB:/app/data

  frontend:
    image: monaemhamila/devopsfrontend
    depends_on:
      - spring
    networks:
      - internalnet
    ports:
      - "4200:4200"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
    - "--config.file=/etc/prometheus.yml"
    networks:
      - internalnet
    depends_on:
      - spring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - prometheus
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
